spring.application.name=voluntariaid-backend

spring.datasource.url=jdbc:mysql://localhost:3306/voluntariaid_db
spring.datasource.username=voluntariaid_user
spring.datasource.password=voluntariaid_password
spring.jpa.hibernate.ddl-auto=update
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
