CREATE TABLE pais (
                      id BIGINT AUTO_INCREMENT PRIMARY KEY,
                      nome VARCHAR(255) NOT NULL
);

CREATE TABLE cidade (
                        id BIGINT AUTO_INCREMENT PRIMARY KEY,
                        nome VARCHAR(255) NOT NULL,
                        pais_id BIGINT,
                        FOREIGN KEY (pais_id) REFERENCES pais(id)
);

-- Países
INSERT INTO pais (id, nome) VALUES
                                (1, 'Brasil'),
                                (2, 'Argentina'),
                                (3, 'Chile');

-- Cidades do Brasil
INSERT INTO cidade (id, nome, pais_id) VALUES
                                           (1, 'São Paulo', 1),
                                           (2, 'Rio de Janeiro', 1),
                                           (3, 'Belo Horizonte', 1),
                                           (4, 'Brasília', 1),
                                           (5, 'Curitiba', 1),
                                           (6, 'Porto Alegre', 1),
                                           (7, 'Recife', 1),
                                           (8, 'Salvador', 1),
                                           (9, 'Fortaleza', 1),
                                           (10, 'Manaus', 1),
                                           (11, 'Belém', 1),
                                           (12, 'Goiânia', 1),
                                           (13, 'Campinas', 1),
                                           (14, 'São Luís', 1),
                                           (15, 'Maceió', 1),
                                           (16, 'Natal', 1),
                                           (17, 'João Pessoa', 1),
                                           (18, 'Teresina', 1),
                                           (19, 'Aracaju', 1),
                                           (20, 'Cuiabá', 1),
                                           (21, 'Campo Grande', 1),
                                           (22, 'Florianópolis', 1),
                                           (23, 'Macapá', 1),
                                           (24, 'Palmas', 1),
                                           (25, 'Ribeirão Preto', 1),
                                           (26, 'Santos', 1),
                                           (27, 'Uberlândia', 1),
                                           (28, 'Sorocaba', 1),
                                           (29, 'Londrina', 1),
                                           (30, 'Maringá', 1),
                                           (31, 'Joinville', 1),
                                           (32, 'Blumenau', 1),
                                           (33, 'Pelotas', 1),
                                           (34, 'Caxias do Sul', 1),
                                           (35, 'Feira de Santana', 1),
                                           (36, 'Juiz de Fora', 1),
                                           (37, 'São José dos Campos', 1),
                                           (38, 'Anápolis', 1),
                                           (39, 'Canoas', 1),
                                           (40, 'Vitória', 1),
                                           (41, 'Itabuna', 1),
                                           (42, 'Ilhéus', 1),
                                           (43, 'Niterói', 1),
                                           (44, 'Petrolina', 1),
                                           (45, 'Marabá', 1),
                                           (46, 'Boa Vista', 1),
                                           (47, 'Porto Velho', 1),
                                           (48, 'Ji-Paraná', 1),
                                           (49, 'Aparecida de Goiânia', 1),
                                           (50, 'Franca', 1);

-- Cidades da Argentina
INSERT INTO cidade (id, nome, pais_id) VALUES
                                           (51, 'Buenos Aires', 2),
                                           (52, 'Córdoba', 2),
                                           (53, 'Rosario', 2),
                                           (54, 'Mendoza', 2),
                                           (55, 'La Plata', 2),
                                           (56, 'Tucumán', 2),
                                           (57, 'Mar del Plata', 2),
                                           (58, 'Salta', 2),
                                           (59, 'Santa Fe', 2),
                                           (60, 'San Juan', 2),
                                           (61, 'Resistencia', 2),
                                           (62, 'Neuquén', 2),
                                           (63, 'Santiago del Estero', 2),
                                           (64, 'Corrientes', 2),
                                           (65, 'Bahía Blanca', 2),
                                           (66, 'Posadas', 2),
                                           (67, 'San Luis', 2),
                                           (68, 'Formosa', 2),
                                           (69, 'Jujuy', 2),
                                           (70, 'Río Cuarto', 2),
                                           (71, 'Concordia', 2),
                                           (72, 'San Rafael', 2),
                                           (73, 'Catamarca', 2),
                                           (74, 'San Nicolás', 2),
                                           (75, 'Tandil', 2),
                                           (76, 'Comodoro Rivadavia', 2),
                                           (77, 'Paraná', 2),
                                           (78, 'San Fernando del Valle', 2),
                                           (79, 'Trelew', 2),
                                           (80, 'Villa María', 2),
                                           (81, 'Río Gallegos', 2),
                                           (82, 'Rafaela', 2),
                                           (83, 'Gualeguaychú', 2),
                                           (84, 'Ushuaia', 2),
                                           (85, 'Pergamino', 2),
                                           (86, 'Zárate', 2),
                                           (87, 'Olavarría', 2),
                                           (88, 'Mercedes', 2),
                                           (89, 'Esquel', 2),
                                           (90, 'Junín', 2),
                                           (91, 'La Rioja', 2),
                                           (92, 'San Carlos de Bariloche', 2),
                                           (93, 'Reconquista', 2),
                                           (94, 'Villa Carlos Paz', 2),
                                           (95, 'Azul', 2),
                                           (96, 'Rawson', 2),
                                           (97, 'General Roca', 2),
                                           (98, 'Chivilcoy', 2),
                                           (99, 'Luján', 2),
                                           (100, 'Cipolletti', 2);

-- Cidades do Chile
INSERT INTO cidade (id, nome, pais_id) VALUES
                                           (101, 'Santiago', 3),
                                           (102, 'Valparaíso', 3),
                                           (103, 'Concepción', 3),
                                           (104, 'La Serena', 3),
                                           (105, 'Antofagasta', 3),
                                           (106, 'Temuco', 3),
                                           (107, 'Iquique', 3),
                                           (108, 'Rancagua', 3),
                                           (109, 'Talca', 3),
                                           (110, 'Arica', 3),
                                           (111, 'Chillán', 3),
                                           (112, 'Copiapó', 3),
                                           (113, 'Punta Arenas', 3),
                                           (114, 'Puerto Montt', 3),
                                           (115, 'Osorno', 3),
                                           (116, 'Calama', 3),
                                           (117, 'Quillota', 3),
                                           (118, 'Curicó', 3),
                                           (119, 'San Antonio', 3),
                                           (120, 'Los Andes', 3),
                                           (121, 'Melipilla', 3),
                                           (122, 'San Felipe', 3),
                                           (123, 'Cauquenes', 3),
                                           (124, 'Linares', 3),
                                           (125, 'Castro', 3),
                                           (126, 'Los Ángeles', 3),
                                           (127, 'Valdivia', 3),
                                           (128, 'Villarrica', 3),
                                           (129, 'La Calera', 3),
                                           (130, 'San Bernardo', 3),
                                           (131, 'Colina', 3),
                                           (132, 'Paine', 3),
                                           (133, 'Maipú', 3),
                                           (134, 'Peñaflor', 3),
                                           (135, 'Recoleta', 3),
                                           (136, 'Ñuñoa', 3),
                                           (137, 'Macul', 3),
                                           (138, 'Puente Alto', 3),
                                           (139, 'Vitacura', 3),
                                           (140, 'Providencia', 3),
                                           (141, 'Las Condes', 3),
                                           (142, 'Lo Barnechea', 3),
                                           (143, 'La Florida', 3),
                                           (144, 'Estación Central', 3),
                                           (145, 'Pedro Aguirre Cerda', 3),
                                           (146, 'San Miguel', 3),
                                           (147, 'El Bosque', 3),
                                           (148, 'Pudahuel', 3),
                                           (149, 'Cerrillos', 3),
                                           (150, 'Independencia', 3);
